{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metaflow-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metaflow.labels" . | nindent 4 }}
  annotations:
    {{- include "metaflow.annotations" . | nindent 4 }}
    {{- if .Values.serviceAccount.annotations }}{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}{{- end }}
{{- end }}
