apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ if .Values.backup.createPvc }}{{ .Release.Name }}-kubegres-backup-pvc{{ else }}{{ .Values.backup.backupPvcName }}{{ end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metaflow.labels" . | nindent 4 }}
  annotations:
    {{- include "metaflow.annotations" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.backup.backupPvcSize }}
  selector:
    matchLabels:
      {{- include "metaflow.labels" . | nindent 6 }}
  storageClassName: {{ .Values.backup.backupStorageClass }}